"""The codes the API puts in its error envelope."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Every `code` the API documents, as the OpenAPI `ErrorCode` enum lists them.

    `APIError.code` stays a plain string, so a code the API adds later still arrives. Compare it with these members,
    which equal their codes, and never match on `message`.
    """

    INVALID_REQUEST = "invalid_request"
    """The request is malformed or failed validation."""
    INVALID_API_KEY = "invalid_api_key"
    """The API key is missing or not recognized."""
    API_KEY_DISABLED = "api_key_disabled"
    """The API key is disabled; it can be enabled again."""
    API_KEY_REVOKED = "api_key_revoked"
    """The API key was revoked and can never be used again."""
    API_KEY_EXPIRED = "api_key_expired"
    """The API key is past its expiry date."""
    INSUFFICIENT_BALANCE = "insufficient_balance"
    """The organization's balance is too low for this request."""
    SPEND_LIMIT_EXCEEDED = "spend_limit_exceeded"
    """The request would take the API key over its monthly spend limit."""
    INSUFFICIENT_PERMISSIONS = "insufficient_permissions"
    """The API key lacks the permission this request needs."""
    IP_NOT_ALLOWED = "ip_not_allowed"
    """The request's IP address is not on the API key's allowlist."""
    NO_ORGANIZATION = "no_organization"
    """The API key belongs to a user without an organization."""
    VOICE_UNAVAILABLE = "voice_unavailable"
    """The voice_id is not usable by this account."""
    INVALID_BOT_SECRET = "invalid_bot_secret"
    """The bot secret is wrong."""
    FORBIDDEN = "forbidden"
    """This API key is not allowed to make this request."""
    NOT_FOUND = "not_found"
    """The route or resource does not exist in this organization."""
    MODEL_NOT_FOUND = "model_not_found"
    """The requested model does not exist or is not available."""
    METHOD_NOT_ALLOWED = "method_not_allowed"
    """The HTTP method is not supported on this route."""
    CONFLICT = "conflict"
    """The request conflicts with the current state of the resource."""
    IDEMPOTENCY_CONFLICT = "idempotency_conflict"
    """The Idempotency-Key was already used with a different request."""
    GONE = "gone"
    """The resource is no longer available."""
    JOB_NOT_FINISHED = "job_not_finished"
    """The TTS job has not finished yet."""
    JOB_FAILED = "job_failed"
    """The TTS job failed and has no audio."""
    AUDIO_EXPIRED = "audio_expired"
    """The TTS job's audio is past its retention window."""
    INPUT_TOO_LARGE = "input_too_large"
    """The input is over a size limit."""
    UNSUPPORTED_MEDIA_TYPE = "unsupported_media_type"
    """The uploaded media type is not supported."""
    BATCH_TOO_LARGE = "batch_too_large"
    """The batch contains too many embedding inputs."""
    TOO_MANY_DOCUMENTS = "too_many_documents"
    """The request contains too many documents to rerank."""
    CONTEXT_LENGTH_EXCEEDED = "context_length_exceeded"
    """The prompt plus max_tokens exceeds the model's context length."""
    UPSTREAM_REJECTED_INPUT = "upstream_rejected_input"
    """The model server refused the input; retrying it unchanged will not succeed."""
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    """The API key's per-minute request rate was exceeded."""
    CONCURRENCY_LIMIT_EXCEEDED = "concurrency_limit_exceeded"
    """Too many requests are in flight for this API key."""
    UPSTREAM_RATE_LIMITED = "upstream_rate_limited"
    """The model server is at capacity; retry after a moment."""
    TOO_MANY_ACTIVE_JOBS = "too_many_active_jobs"
    """Too many queued or running TTS jobs for this API key."""
    SERVER_ERROR = "server_error"
    """An unexpected error occurred."""
    SYNTHESIS_FAILED = "synthesis_failed"
    """Speech or dialogue generation failed; retry after a moment."""
    TRANSCRIPTION_FAILED = "transcription_failed"
    """Transcription failed; retry after a moment."""
    UPSTREAM_ERROR = "upstream_error"
    """A model or voice service failed; retry after a moment."""
    SERVICE_UNAVAILABLE = "service_unavailable"
    """A required service is temporarily unavailable."""
    STORAGE_FAILED = "storage_failed"
    """Audio was generated but could not be stored for an idempotent retry."""

    def __str__(self) -> str:
        return str(self.value)
